sudo: false
dist: trusty

language: php

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest

before_script:
  - composer install
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs .
  - bash run-wpacceptance.sh

services:
  - mysql
