sudo: false

language: php

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=4.4
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=4.4

before_script:
  - composer install
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      else
        composer global require "phpunit/phpunit=5.7.*"
      fi
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - composer run-script lint
