sudo: false

language: php

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest

before_script:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - ./vendor/bin/phpunit
  - composer run-script lint
