
sudo: false
dist: trusty

language: php

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
      dist: precise

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

script:

  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      vendor/bin/phpunit
	fi
  - composer install
  - composer run-script lint
  - bash run-wpacceptance.sh
services:
  - mysql
