sudo: false

language: php

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=4.4

before_script:
  - composer install

script:
  - phpunit
  - composer run-script lint
