name: Build release zip

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:
  push:
   branches:
    - trunk

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate ZIP file
        uses: 10up/action-wordpress-plugin-build-zip@b9e621e1261ccf51592b6f3943e4dc4518fca0d1 # v1.0.2
