name: PHPUnit

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1']

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: getong/mariadb-action@d6d2ec41fd5588f369be4c9398ce77ee725ca9ea # v1.11

    - name: Set PHP version
      uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: composer update -W

    - name: Setup WP Tests
      run: bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1

    - name: Run PHPUnit
      run: './vendor/bin/phpunit'
